### ISSUE TITLE
Yarn workspace-ზე გადაწყობა

### ISSUE THREAD

**Issue by iarigby** [freeuni-digital-technologies/subject-modules#10]
სამუშაო გარემოზე სათითაოდ არ უნდა იყოს დასაკლონირებელი ყველა რეპოზიტორია და dependency, yarn link გასაკეთებელი და ა.შ

[instructions](https://classic.yarnpkg.com/blog/2017/08/02/introducing-workspaces/). თუ სწორად მახსოვს ერთი რეპოზიტორია საჭიროა და ამისთვის შექვმენი ეს (subject modules).

- [x] yarn workspace კონფიგურაციის გაკეთება
- [x] README.md-ში სამუშაო გარემოს გამართვის/გამოყენების ინსტრუქციები
- [x] README.md-ში სამუშაო გარემოში ახალი რეპოზიტორიის დამატების ინსტრუქცია

**Comment by khokho** [comment]
yarn workspace კი მაქვს subject-module-ში მოწყობილი ახლა და ცალ ცალკე დაკლონვის გარეშე ასე მუშაობს:
```bash
git clone https://github.com/freeuni-digital-technologies/subject-modules --recursive
yarn
yarn build ცალ ცალკე მოდულებში
```
მაგრამ რეალურად ცვლილელების შეტანა ცოტა არაკომფორტულია და პრობლემა submodule ებშია. როგორ გამოვასწორო რომ ვიცოდე ვიზამდი, მაგრამ ვერ ვნახე ვერაფერი. ერთადერთი ის ვარიანტი მაქვს რომ monorepo იყოს subject-modules და ანუ ყველა მოდულს ერთად შეიცავდეს პირდაპირ.

**Comment by iarigby** [comment]
@khokho უი ბოდიში, ეს როგორ ვერ შევამჩნიე. git submoduleები ჰო რა ძალიან მოუხერხებელია ასე ძალიან პარალელურად როცა ვმუშაობთ, ჩემი აზრით ამ ეტაპზე მოვაშოროთ.

ერთი იდეა მაქვს, workspacesში ხომ არის სია რეები გვჭირდება და `setup.sh` იყოს რომელიც უბრალოდ წაიკითხავს მაგ სიას თითოეულზე გაუშვებს 

setup.sh
```sh
node getList.js | xargs -I {} git clone git@github.com:freeuni-digital-technologies/{}`
```

getList.js
```js
const fs = require('fs')
const { worskspaces } =  JSON.parse(fs.readFileSync('package.json')) // აქ path შეიძლება დაჭირდეს
console.log(workspaces.join('\n'))
```

codehskarel და jskarel ტესტერებში jskarelის dependency მოვაშორე იმის გამო რომ yarn link ვცადე და არ მუშაობდა. ინსტრუქცია დაამატე READMEში.

**Comment by khokho** [comment]
კი, მასეთი ვარიანტი ჯობს ნამდვილად. ვცდი ხვალ და ვეცდები რაც შეიძლება კომფორტული იყოს :star2:

**Comment by iarigby** [comment]
აუ გაშვების გარეშეც ვერ ვისვენებ. ის ბოლო ერთხაზიანი არ იმუშავებს, git pull როცა unsaved changes გამო გაფეილდება მერე cd .. არ გამოვა. მე მესამე შელში შევიდოდი ოღონდაც ბეშის if/else არ დავწერო 🙃 
```sh
node getList.js | xargs -I {} bash -c 'bash -c "cd {} && git pull" || git clone git@github.com:freeuni-digital-technologies/{}'
```
