### ISSUE TITLE
urgent 

### ISSUE THREAD

**Issue by iarigby** [freeuni-digital-technologies/subject-modules#12]
არ ვიცი ვილაპარაკეთ თუ არა ამაზე, მაგრამ კარელის ნაწილში ვიყენებ codehs სამუშაო გარემოს (და წინასწარ შექმნილ სავარჯიშოებს). აი ეს კურსია https://codehs.com/go/915DE (კოდის შეყვანა თუ მოგთხოვა https://codehs.com/go/915DE)

- codehskarel-tester გავაკეთე და მაგით უნდა ჩანაცვლდეს module-karelში ტესტერი. წესით უპრობლემოდ უნდა ჩანაცვლდეს და მეტი ცვლილება არ ჭირდება, მაგრამ დავალებების ტესტერებს რომ დაამატე ნახე რომ სწორმა კოდმა გაიაროს. main შევცვალე start-ით (სატესტო ფაილშიც) და რამდენიმე ფუნქციის სახელი rewire-თან.

## პირველი ორი დავალება
დავალებები შეიცვალა და ტესტერებია გასაკეთებელი
#### პირველი
მეოთხე უჯრაზე დევს ბურთი, უნდა მივიდეს და აიღოს
https://codehs.com/lms/assignment/41699405/
#### მეორე
უნდა გაუყვეს ქუჩას მანამ, სანამ ყვითელი ბურთები დევს (ერთი ტესტი ისე იყოს რომ მაგალითად 5 ბურთი დევს და მერე გამოტოვება მერე კიდევ ერთი და შემოწმდეს რომ არ გადავიდეს იმ გამოტოვებაზე)
https://codehs.com/lms/assignment/41699499/

`NOTE` .github.io რეპოზიტორიას სახელი გადავარქვი და ახალი შევქმენი. წაშალე და თავიდან დააკლონირე

მოკლედ, თასქები
- [x] პირველი ორი დავალების ტესტერის შეცვლა და შემოწმება
- [x] კლასრუმზე პირველი ორი დავალების დამატება (პირველის დედლაინი ახლა ხუთშაბათს, მეორის მომავალ ხუთშაბათს). პირობაში ეწეროს codehs ლინკი და დავალების ახალი ინსტრუქცია  https://freeuni-digital-technologies.github.io/homework/. მეილის ტექსტშიც ჩაანაცვლე ინსტრუქციის ლინკი
- [x] სერვერზე კლასრუმის მონაცემების შეცვლა და პირველი ორი დავალების შემოწმებაზე გაშვება

**Comment by khokho** [comment]
donezou

**Comment by iarigby** [comment]
@khokho <3
