### ISSUE TITLE
khanacademy დავალებების ჩათვლა

### ISSUE THREAD

**Issue by iarigby** [freeuni-digital-technologies/subject-modules#18]
ხანის აკადემიის მასწავლებლის ანგარიშზე სხვა მასწავლებლების დამატება არ არის, ამიტომ user/pass მოგწერეთ მესენჯერში (search "user:")

csv ფაილის გადმოწერა შესაძლებელია ამ გვერდზე. ამის პარსერი მარტივი სკრიპტია დასაწერი. 
csv entryებში მძიმე არის სახელებში და ეგ გასათვალისწინებელია (regex fun)

ძაან ჯახირა მაგალითი
```js
const results = {}

students.forEach(s => results[s] = {})


// იდეაში სჯობს Submission ფორმატით იყოს და tests სიაში შევიდეს დავალების სახელი/ლინკი და მერე მეილზე ეგრევე გაეგზავნება, მაგრამ იგივე ლოგიკაა
csvEntries.forEach(e => results[e.student][e.title] = getScore(e)) // getScore 1 ან 0ს აბრუნებს
// აქ ერორი იქნება იმ სტუდენტებზე რომლებიც ხანზე არიან და jsonში არა (არასწორად/ორჯერ დარეგისტრირებული
// და მაგათ ვიკიდებთ

numberOfTasks = Set(csvEntries.map(e => e.title)).size() 
// და მერე თითოეული სტუდენტის result იქნება დაგროვებული ქულა / numberOfTasks
```

https://ka.khanacademy.org/coach/class/5037508371300352/settings

feedback მისდით:
- დედლაინამდე ორი დღით ადრე
- დედლაინის მეორე დღეს

feedback
- თუ ყველა ამოცანა გაკეთებული აქვს, უბრალოდ ეწეროს, რომ ყველაფერი ჩააბარა
- თუ არცერთი გაუკეთებია, ეგ ეწეროს
- ნაწილი თუ გაკეთებულია და ნაწილი არა, ეწეროს რომელი აკლია
- თუ არ დარეგისტრირებულა (students.json-ში არის მაგრამ ხანის აკადემიაზე არა), პირველ რიგში შეიძლება მეტსახელი არ შეიცვალა (ნახოს ხანის აკადემიის ინსტრუქცია). და როგორც კი შეიცვლის ჩაეთვლება ჩვეულებრივ. ან არ დარეგისტრირებულა (მაინც ნახოს ხანის აკადემიის ინსტრუქცია)

**Comment by iarigby** [comment]
@khokho ჰო, ორი დავალებაა სულ და ორჯერ შემოწმდება თითო, სამომავლოდ არ იგეგმება მაგის ცვლილება. ლინკი მარტივად თუ არ მუშაობს სხვა ვარიანტის გარკვევა არც ღირს.

**Comment by iarigby** [comment]
კვირას არის დედლაინი

**Comment by iarigby** [comment]
@khokho  ეს მოდული დასრულებულია, ჰო?

**Comment by khokho** [comment]
ახალ დავალებებზე ცოტა სხვა ფორმატშია csv რატომღაც ამიტო ცოტა გადაკეთება უნდა. დღეს ან ხვალ ვიზამ.

 დედლაინამდე ფიდბექი არ იყო საჭირო იმიტორო წინაზე არ ყოფილა დიდად პრობლემები.
