### ISSUE TITLE
migrate to db

### ISSUE THREAD

**Issue by iarigby** [freeuni-digital-technologies/subject-modules#8]
module-js/karelს კონფიგურაციაში ქონდეს მისამართი და ორივე მაგას დაუკავშირდეს.

## querying
- მარტივ file based database  https://github.com/typicode/lowdb
- მგონი ამ მოდულში უნდა იყოს Submission კლასიც (classroom-api#5)
- db ცალკე მოდული იქნება და api-ს გარდა cli ინტერფეისს ექნება print ან რამე ეგეთი ფუნქცია, რომელსაც ფილტრი ექნება და კონკრეტული დავალების ან სტუდენტის სტატუსს ეგრე გაიგებ (json output). შესაბამისად ქულების დათვლას ცალკე სკრიპტის დაწერა არ დაჭირდება.
- ყველა დავალებას დაემატოს runid, status (ახლა .jsonები რითიც არის)

**Comment by iarigby** [comment]
@khokho ეს მოდული დასრულებულია, ჰო?

**Comment by iarigby** [comment]
@khokho ამაზე რა ვითარებაა?

**Comment by khokho** [comment]
შესანახად გამოსადეგია უკვე.
წინა დავალების ქულებსაც გადავიტან და შეჯამებული ქულების ექსპორტის ფუნქციებსაც დავუწერ მალე.
